name: Deploy on Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Install Dependencies
      run: dotnet restore ./app.sln

    - name: Build
      run: dotnet build --configuration Release ./app.sln

    - name: Publish
      run: dotnet publish ./ValveModHub.Server/ValveModHub.Server.csproj -c Release -o ./serverbrowser

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: WebApp
        path: serverbrowser/*